# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

parameters:
  - name: Servidor
    type: string
    default: ""

pool:
  vmImage: $(NODE)


steps:
- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/projetos-occ/playbook.yml
    TargetFolder: '/tmp/'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script:  bash /tmp/projetos-occ/cria_host.sh ${{ parameters.Sevidor }}
      
- task: Docker@2
  displayName: Executing Container
  inputs:
    command: 'run'
    arguments: '--rm -v /tmp/projetos-occ/:/tmp/ th1d0ker/ansible:centos8 ansible-playbook -i /tmp/projetos-occ/hosts_pipeline  -vvv'

- task: DeleteFiles@1
  displayName: Delete Files
  inputs:
    SourceFolder: '/tmp/Zabbix-maintenance'
    Contents: '**/*'
    RemoveSourceFolder: true