# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

parameters:
  - name: Servidor
    type: string
    default: ""

pool:
  name: $(NODE)
  timeoutInMinutes: 20


steps:
- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/playbook.yml
      **/cria_host.sh
    TargetFolder: '/tmp/'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
     bash /tmp/cria_host.sh ${{ parameters.Servidor }}
     cat /tmp/hosts_pipeline
      
- task: Docker@2
  displayName: Executing Container
  inputs:
    command: 'run'
    arguments: '--rm -v /tmp/:/tmp/ th1d0ker/ansible:centos8 ansible-playbook -i /tmp/hosts_pipeline /tmp/playbook.yml  -vvv'

#- task: DeleteFiles@1
#  displayName: Delete Files
#  inputs:
#    SourceFolder: '/tmp'
#    Contents: '**/*'
#    RemoveSourceFolder: true
