# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

variables:
- name: servidor
  value: $(servidor)
  readonly: true

pool:
  vmImage: $(NODE)

steps:
- script: | 
          pip install pipenv --user
          pipenv run install ansible 
          pipenv run ansible-playbook -i $(servidor) playbook.yml 
  displayName: 'Executando Playbook'
