---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: sync; echo 1 > /proc/sys/vm/drop_caches && sync; echo 2 > /proc/sys/vm/drop_caches
  become: yes