trigger: none
pr: none

parameters:
  - name: Servidor
    type: string
    default: ""

pool:
  name: $(NODE)
  timeoutInMinutes: 20


steps:
- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/playbook.yml
      **/cria_host.sh
    TargetFolder: '/tmp/clswap/'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
     bash /tmp/clswap/cria_host.sh ${{ parameters.Servidor }}
      
- task: Docker@2
  displayName: Executing Container
  inputs:
    command: 'run'
    arguments: '--rm -v /tmp/clswap/:/tmp/clswap llteodoro/ansible:1.0 ansible-playbook -i /tmp/clswap/hosts_pipeline /tmp/clswap/playbook.yml --extra-vars "ansible_user=$(usr_name) ansible_password=$(user_pwd)" -vvv'

- task: DeleteFiles@1
  displayName: Delete Files
  inputs:
    SourceFolder: '/tmp/clswap/'
    Contents: '**/*'
    RemoveSourceFolder: true
